package com.lx.fight.enums;

public enum ResourceEnum {
    MAIN_TANK_UP,
    MAIN_TANK_DOWN,
    MAIN_TANK_RIGHT,
    MAIN_TANK_LEFT,

    DEFAULT_ENEMY_TANK_UP,
    DEFAULT_ENEMY_TANK_DOWN,
    DEFAULT_ENEMY_TANK_RIGHT,
    DEFAULT_ENEMY_TANK_LEFT,

    BULLET_UP,
    BULLET_DOWN,
    BULLET_RIGHT,
    BULLET_LEFT,
    ;

}
